export const servicesData = [
  {n:"01",c:"Data & Intelligence",q:"Still running your business on spreadsheets and email threads?",cta:"→ See how we fix this",desc:"From scattered data to a single source of truth. Data engineering, analytics, dashboards, and AI readiness.",prob:"Most organisations are data rich and insight poor. Reports pile up but don’t drive action.",app:"We build trusted data foundations, design analytics that answer real business questions, and embed insight into the rhythms of how your leaders actually work.",out:["Decision grade data where leaders need it","Reduced time from question to insight","Analytics aligned to strategic priorities","Data governance that builds trust"]},
  {n:"02",c:"AI Strategy & Roadmap",q:"Everyone is talking about AI. You are still figuring out where to start?",cta:"→ Start here",desc:"From confusion to clarity. We map where AI can deliver real value, sequence the steps, and build the business case.",prob:"You’ve seen AI demos, but nothing has actually changed in your operations.",app:"We help you build an AI strategy that starts with your business priorities, not the technology.",out:["A board ready AI strategy tied to business outcomes","Clear prioritisation of use cases","Responsible AI governance from day one","Reduced risk of pilots that go nowhere"]},
  {n:"03",c:"Automation & Operations",q:"Too many people doing the same thing manually, every single day?",cta:"→ Automate the repeat",desc:"Remove manual touchpoints. Automate the repeat. Scale without adding headcount.",prob:"Your best people are stuck in repetitive tasks. Processes break every time someone goes on leave.",app:"We begin with a forensic process audit, identify high impact automation opportunities, and build solutions using RPA, intelligent document processing, and workflow orchestration.",out:["20 to 40% reduction in manual processing time","Processes that survive staff changes","Teams freed for judgement intensive work","Automation roadmap prioritised by ROI"]},
  {n:"04",c:"QA & Assurance",q:"Quality depends on who is doing the work, not how the work is designed?",cta:"→ Quality by design",desc:"Real time quality monitoring, AI powered compliance checks, and exception detection before the client sees it.",prob:"Errors show up only when the client complains. Spot checks are not scalable.",app:"We replace spot check QA with continuous AI monitored quality. Quality becomes a system property, not a person dependency.",out:["QA coverage from spot check to 100%","Errors caught before the client sees them","Consistent quality regardless of shift","Real time quality dashboards"]},
  {n:"05",c:"AI Governance & Trust",q:"You are using AI but do not fully trust the output?",cta:"→ AI you can trust",desc:"Explainability, audit trails, and regulatory readiness. The glass around the flame that makes AI safe to carry.",prob:"No one knows how the AI made that decision. Regulators are asking questions you cannot answer yet.",app:"We build the governance layer first: explainability standards, audit trail requirements, and data privacy frameworks.",out:["AI governance framework before the regulator asks","Full audit trails for every AI decision","Explainability built into every deployment","Board level confidence in AI risk management"]},
  {n:"06",c:"Transformation Consulting",q:"You have been transforming for years but operations still feel the same?",cta:"→ Real transformation",desc:"Operating model redesign, change management, and target operating models.",prob:"New systems were implemented. Old habits stayed. Millions spent, years lost, and the original problems still intact.",app:"We start with outcomes, work backwards to the changes required, and design transformation sequenced for early value.",out:["Transformation that delivers value in months","Reduced complexity and cost of ownership","Technology decisions driven by need","Change that actually sticks"]},
  {n:"07",c:"Managed Operations",q:"You want to focus on growth but operations keep pulling you back?",cta:"→ We run it. You grow.",desc:"We run the operation. Human in the loop where it matters. AI and automation where it scales.",prob:"Hiring is hard. Retaining is harder. Operations cannot wait.",app:"Lantern’s managed operations model gives you experienced, integrated teams that run your processes with automation, continuous improvement, and operational discipline built in.",out:["20 to 30% capacity gain without new headcount","Consistent service quality with improvement built in","Operational resilience and continuity","Leadership bandwidth freed for strategy"]},
  {n:"08",c:"Third Party Solutions",q:"The vendor delivered the system. Who is delivering the outcomes?",cta:"→ Own the outcomes",desc:"Implementation partner for third party platforms. We deliver outcomes, not just go lives.",prob:"Your third party platform is live but no one really knows how to use it.",app:"We are the implementation partner who stays until outcomes arrive. Stakeholder management, configuration, integration automation, training, and post go live support.",out:["Platforms that are actually adopted","Outcomes measured from day one","Integration with existing workflows","Self sufficiency built into your team"]},
  {n:"09",c:"People & Change",q:"New system went live. Nobody changed how they work?",cta:"→ Make change stick",desc:"Adoption strategy, change management, and cultural alignment. Because technology only works when people use it.",prob:"Millions invested in new platforms. Adoption sits at 30%. Teams revert to old habits within weeks.",app:"We embed change from the start, designing adoption journeys that respect how people actually work.",out:["Adoption rates that justify the investment","Change plans tied to business outcomes","Leadership aligned and visibly engaged","Lasting behavioural shift, not training decks"]}
];

export const heroQs = [
  {q:"Too many people doing the same thing manually, every single day?",si:2,ct:"→ Automate the repeat"},
  {q:"Everyone is talking about AI. You are still figuring out where to start?",si:0,ct:"→ Start here"},
  {q:"You want to focus on growth but operations keep pulling you back?",si:6,ct:"→ We run it. You grow."},
  {q:"Quality depends on who is doing the work, not how the work is designed?",si:3,ct:"→ Quality by design"},
  {q:"New system went live. Nobody changed how they work?",si:8,ct:"→ Make change stick"}
];
