export const servicesData = [
  {n:"01",c:"Data & Intelligence",q:"Still running your business on spreadsheets and email threads?",cta:"→ See how we fix this",desc:"From scattered data to a single source of truth. Data engineering, analytics, dashboards, and AI readiness.",prob:"Most organisations are data rich and insight poor. Reports pile up but don’t drive action.",app:"We bring together the data your business needs, turn it into meaningful insights and place them where your teams need them to act.",out:["Real time insights for better decision making","Analytics aligned to strategic priorities","One view across all your functions, no fragmented reports","Trusted data with a strong governance foundation"]},
  {n:"02",c:"AI Strategy & Roadmap",q:"AI is everywhere. But which AI investments will truly drive revenue, reduce costs, and improve your bottom line?",cta:"→ Start here",desc:"From confusion to clarity. We map where AI can deliver real value, sequence the steps, and build the business case.",prob:"You’ve seen AI demos, but nothing has actually changed in your operations.",app:"From confusion to clarity. We help you identify where AI can create value, where it makes sense to invest and help you turn those opportunities into business outcomes.",out:["AI strategy based on your current and future goals","Clear prioritisation of use cases","Responsible AI governance from day one","AI investments realised through improved business outcomes"]},
  {n:"03",c:"Automation & Operations",q:"Too many people doing the same thing manually, every single day?",cta:"→ Automate the repeat",desc:"Remove manual touchpoints. Automate the repeat. Scale without adding headcount.",prob:"Your best people are stuck in repetitive tasks. Processes break every time someone goes on leave.",app:"We analyse existing processes, identify inefficiencies, design and implement solutions using intelligent automation, low-code platforms, system integrations and workflow orchestration where they add the most value.",out:["Reduced manual processing time","Processes that run with minimal manual intervention","Teams freed up for higher value work","Automation roadmap prioritized by ROI"]},
  {n:"04",c:"QA & Assurance",q:"Quality depends on who is doing the work, not how the work is designed?",cta:"→ Quality by design",desc:"Real time quality monitoring, automated compliance checks and AI assisted exception detection before the client sees it.",prob:"As volumes grow, maintaining consistent quality becomes harder. Issues are often discovered only after they have reached the client.",app:"We build quality into the process with automated checks that detect issues to ensure only quality products and services reach your customers.",out:["100% Quality Assurance","Consistent quality throughout","Errors caught before the client sees them","Real time quality dashboards"]},
  {n:"05",c:"AI Governance & Trust",q:"You are using AI but do not fully trust the output?",cta:"→ AI you can trust",desc:"Make AI decisions clear, controlled, and accountable.",prob:"AI may give you an answer, but you need to know why, whether it can be trusted, and whether you can defend it.",app:"We build the controls around AI so every important decision can be explained, tracked, and reviewed.",out:["Know why AI made a recommendation","Trace decisions when something goes wrong","Reduce compliance and regulatory risk","Scale AI without losing control"]},
  {n:"06",c:"Transformation Consulting",q:"You have been transforming for years but operations still feel the same?",cta:"→ Real transformation",desc:"From where your organisation is today to where it needs to be next—redesigning how the business operates, enabling change and building the capabilities needed to sustain growth.",prob:"New systems were implemented. Old habits stayed. Millions spent, years lost, and the original problems still intact.",app:"We start with outcomes, work backwards to the changes required, and design transformation sequenced for early value.",out:["Targeted business outcomes achieved","Productivity and efficiency gains","Revenue or growth opportunities converted into results","Improvements sustained beyond implementation"]},
  {n:"07",c:"Managed Operations",q:"You want to focus on growth but operations keep pulling you back?",cta:"→ We run it. You grow.",desc:"We take ownership of day-to-day operations, combining human expertise, AI and automation to deliver consistent performance and continuous improvement.",prob:"Hiring is hard. Retaining is harder. Operations cannot wait.",app:"Lantern’s managed operations model gives you experienced, integrated teams that run your processes with automation, continuous improvement, and operational discipline built in.",out:["Capacity gain without additional headcount","Lower cost and effort of day-to-day operations","Consistent service quality with improvement built in","Leadership bandwidth freed for strategy"]},
  {n:"08",c:"Third Party Solutions",q:"The vendor delivered the system. Who is delivering the outcomes?",cta:"→ Own the outcomes",desc:"Implementation partner for third party platforms. We deliver outcomes, not just go lives.",prob:"Your third party platform is live but no one really knows how to use it.",app:"We are the implementation partner who stays until outcomes arrive. We connect the platform to your business—not just to your technology environment.",out:["A connected operating environment across systems and functions","Faster realisation of the platform's intended value","Smoother processes with fewer integration gaps","Greater control over the platform's ongoing business value"]},
  {n:"09",c:"People & Change",q:"The best system in the market creates real value only when your people adopt it and embrace new ways of working.",cta:"→ Make change stick",desc:"Technology can enable change, but people make it real. We help teams understand, adopt and embed new ways of working so the organisation can realise the value of the change.",prob:"New systems are implemented, but adoption remains low and teams gradually return to familiar ways of working—leaving the expected value of the investment unrealised.",app:"We embed change from the start, designing adoption journeys that respect how people actually work.",out:["Higher adoption and utilisation of new systems","Faster realisation of the intended business benefits","Smoother transition with less operational disruption","New ways of working that sustain over time"]}
];

export const heroQs = [
  {q:"Too many people doing the same thing manually, every single day?",si:2,ct:"→ Automate the repeat"},
  {q:"Everyone is talking about AI. You are still figuring out where to start?",si:1,ct:"→ Start here"},
  {q:"You want to focus on growth but operations keep pulling you back?",si:6,ct:"→ We run it. You grow."},
  {q:"Quality depends on who is doing the work, not how the work is designed?",si:3,ct:"→ Quality by design"},
  {q:"New system went live. Nobody changed how they work?",si:8,ct:"→ Make change stick"}
];
